version: 2.1

jobs:
  build-image:
    environment:
      IMAGE_NAME: tomlhermenier/node-js-sample
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "Build image"
          command: "docker build . -t \"$IMAGE_NAME\""
      - run:
          name: "Test image"
          command: "docker run -d -p8080:8080 \"$IMAGE_NAME\""
      - run:
          name: "Test connexion"
          command: "curl localhost:8080"
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-latest:
    environment:
      IMAGE_NAME: tomlhermenier/node-js-sample"
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: "docker load -i /tmp/workspace/image.tar"
      - run:
          name: Login
          command:
            "echo \"$DOCKERHUB_PASSWORD\" | docker login -u \"$DOCKERHUB_USERNAME\" --password-stdin"
      - run:
          name: Push
          command: "docker push \"$IMAGE_NAME\""

workflows:
  docker-build-image:
    jobs:
      - build-image
      - publish-latest:
          requires:
            - build-image