version: 2.1

jobs:
  build-image:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "Build image"
          command: "docker build . -t \"$DOCKERHUB_USERNAME\"/node-js-sample"
      - run:
          name: "Test image"
          command: "docker run -d -p8080:8080 \"$DOCKERHUB_USERNAME\"/node-js-sample"
      - run:
          name: "Test connexion"
          command: "curl localhost:8080"
      - run:
          name: "Login"
          command: "echo \"$DOCKERHUB_PASSWORD\" | docker login -u \"$DOCKERHUB_USERNAME\" --password-stdin"
      - run:
          name: "Push"
          command: "docker push \"$DOCKERHUB_USERNAME\"/node-js-sample"


workflows:
  docker-build-image:
    jobs:
      - build-image