version: 2.1

jobs:
  build-image:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "Build image"
          command: "docker build . -t node-js-sample"
      - run:
          name: "Test image"
          command: "docker run -d -p8080:8080 node-js-sample"
      - run:
          name: "Test connexion"
          command: "curl localhost:8080"
  publish-latest:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker
      - run:
          name: "Login"
          command: "echo “$DOCKERHUB_PASSWORD” | docker login -u “$DOCKERHUB_USERNAME” — password-stdin"
      - run:
          name: "Push"
          command: "docker push node-js-sample"

workflows:
  docker-build-image:
    jobs:
      - build-image
      - publish-latest:
          requires:
            - build-image
