version: 2.1

jobs:
  build-image:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "Build image"
          command: "docker build . -t node-js-sample"
      - run:
          name: "Test image"
          command: "docker run -d -p8080:8080 node-js-sample"
      - run:
          name: "t"
          command: "sleep 1"
      - run:
          name: "Test connexion"
          command: "curl localhost:8080"
  publish-latest:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker
      - run:
          name: Publish Docker Image to Docker Hub
          command: "docker login -u \"$DOCKERHUB_USERNAME\" -p \"$DOCKERHUB_PASSWORD\" 
            docker push node-js-sample"

workflows:
  docker-build-image:
    jobs:
      - build-image
