version: 2.1

jobs:
  build-image:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build image"
          command: "docker build . -t node-js-sample"
      - run:
          name: "Test image"
          command: "docker run -d -p8080:8080 node-js-sample"
      - run:
          name: "Test connexion"
          command: "if [[ $(curl -o /dev/null -w '%{http_code}' http://localhost:8080/.well-known/apollo/server-health) == 200 ]]; then echo 'Success'; exit 0; else exit1; fi"

workflows:
  docker-build-image:
    jobs:
      - build-image
