version: 2.1

jobs:
  build-image:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build image"
          command: "docker build . -t node-js-sample"

workflows:
  say-hello-workflow:
    jobs:
      - build-image
